name: Backend Lint

on:
  push:
    paths:
      - "backend/**"
      - "scripts/update-deps.sh"
      - "package.json"
      - ".github/workflows/lint-backend.yml"
  pull_request:
    paths:
      - "backend/**"
      - "scripts/update-deps.sh"
      - "package.json"
      - ".github/workflows/lint-backend.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, embeddings, eval]
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        working-directory: backend/${{ matrix.service }}
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Ruff lint
        working-directory: backend/${{ matrix.service }}
        run: poetry run ruff check .

      - name: Black format check
        working-directory: backend/${{ matrix.service }}
        run: poetry run black --check .
